### PR TITLE
improve run-on suggestions for camel case words

### PR DESCRIPTION
**Pull request by jaumeortola**

### CODE REVIEW

**Comment by dweiss** [comment]
This will generate some (a lot?) false-positives. Like "aloft" could be "a loft" but can also be "aloft".

**Comment by milekpl** [comment]
Hm, I guess the following cases should work as well:

`Assertions.assertThat(spell.replaceRunOnWords("AbakaAbace")).contains("Abaka Abace");
    Assertions.assertThat(spell.replaceRunOnWords("abakaAbace")).contains("abaka Abace");
`

Notice the second one.

**Comment by dweiss** [comment]
I've reverted this, temporarily. See @milekpl 's comment

**Comment by milekpl** [comment]
Oh, I did remove my comment because it was false! :) I added the junit test cases. I wrote my comments before running the test cases and saw that they worked, so I deleted it immediately. Sorry!

**Comment by dweiss** [comment]
Should I merge it in then?

**Comment by milekpl** [comment]
Sure. Please merge. Note that test cases will fail without the merge as well.

**Comment by dweiss** [comment]
Done! I'll try to prepare a release over the next few days.

**Pull request merged**
