### PR TITLE
Update Speller.java

### PR DESCRIPTION
**Pull request by Mility**
check the separate words(eg.misspelled the word "together" to "to gether")

### CODE REVIEW

**Comment by milekpl** [comment]
You must mean something altogether different, namely replacing "to gether" with "together", right? Why don't you add a property for the configuration file to make this configurable by the dictionary author?

**Comment by Mility** [comment]
yes, I want to add this function in speller.

**Comment by Mility** [comment]
and I dont know what do you mean.

**Comment by milekpl** [comment]
Well, our dictionaries come with property files. Using those, you can choose whether you want to, for example, ignore diacritic characters or split words written together (runon words). See here for the list of constants in the property files:

http://wiki.languagetool.org/hunspell-support

We should have another property, for example, "fsa.dict.speller.joinwords". You can see in the code that if you select runon words, the speller automatically tries to split words. And now it could also try to join them.

Hope this helps.

**Comment by Mility** [comment]
Thanks.

**Comment by Mility** [comment]
https://github.com/morfologik/morfologik-stemming/pull/47 
https://github.com/morfologik/morfologik-stemming/pull/48
https://github.com/morfologik/morfologik-stemming/pull/49
I don't know how to merge those pull requests, and haven't test it.

**Pull request closed without merging**
